Automatic commit for version v1.0.343-main

diff --git a/run-example b/run-example
--- a/run-example
+++ b/run-example
@@ -145,7 +145,7 @@ read_config() {
 }
 
 function listExamples() {
-    cat docker-compose/host-networking/*yml |
+    find docker-compose/host-networking -name \*yml | xargs cat |
         grep -e '^#' |
         sed -e 's/# Norsk Media example: //' \
             -e 's/#/ /' \
@@ -158,6 +158,8 @@ function startExample() {
     local -r runSource=${3}
     local -r dockerComposeCmd=$(dockerComposeCmd)
     local candidate
+    local -a matches=()
+    local file
 
     if [ -z "$dockerComposeCmd" ]; then
         echo "Error: Unable to find docker-compose - exiting"
@@ -165,23 +167,28 @@ function startExample() {
     fi
 
     pushd "$ymlPath" >/dev/null
-    case "$exampleName" in
-    [0-9][0-9]) # User gave just the example number
-        candidate=$(ls -1 "$1_"*".yml" 2>/dev/null || true | head -1)
-        ;;
-    [0-9][0-9]_*.yml) # Full match
-        candidate=$(ls -1 "$1" 2>/dev/null || true | head -1)
-        ;;
-    [0-9][0-9]_*) # Full name of example (no extension)
-        candidate=$(ls -1 "$1.yml" 2>/dev/null || true | head -1)
-        ;;
-    *)
-        candidate=$(ls -1 [0-9][0-9]"_$1.yml" 2>/dev/null || true | head -1)
-        ;;
-    esac
+
+    for file in $(find . -name \*yml -type f); do
+        if [[ "$file" =~ $exampleName ]]; then
+            matches+=(${file#./})
+        fi
+    done
+
+    if [ ${#matches[@]} -eq 0 ]; then
+        echo "Error: unknown example '$exampleName'"
+        exit 1
+    fi
+    if [ ${#matches[@]} -gt 1 ]; then
+        echo "Error: '$exampleName' is ambiguous, I found: ${matches[@]}"
+        exit 1
+    fi
+
+    candidate=${matches[0]}
+
     popd >/dev/null
 
     local -r dcFile="$ymlPath/$candidate"
+
     if [ ! -f "$dcFile" ]; then
         echo "Error: example not found $exampleName"
         exit 1
@@ -451,7 +458,7 @@ function main() {
                 usage
                 exit 1
             fi
-            downloadMediaAssets
+#            downloadMediaAssets
             echo "Stopping any current example"
             echo
             stopExample
